[*]fixed bug:PermissionError: [WinError 5]
k4yt3x/video2x pull request #385
Opened 2020-10-14 02:49 UTC by zxsean

Try to fix this issue:
https://github.com/k4yt3x/video2x/issues/321

2020-10-14 03:18 UTC, k4yt3x requested changes

2020-10-14 03:18 UTC, k4yt3x commented on src/upscaler.py
> +                except:
Please do not use bare `except`

2020-10-14 03:18 UTC, k4yt3x commented on src/upscaler.py
> +                        Avalon.info(_("Change file's attribute."))
This line is not clear. What file's what attribute are you changing?
Also, there should be no periods at the end of command line outputs.

2020-10-14 03:18 UTC, k4yt3x commented on src/upscaler.py
> +                        for root, dirs, files in os.walk(self.extracted_frames):
Do not use `os` for file operations. Use `pathlib.Path`.

2020-10-14 03:21 UTC, zxsean commented
ok~ thx i will fix this~

2020-10-14 05:56 UTC, k4yt3x requested changes

2020-10-14 05:56 UTC, k4yt3x commented on src/upscaler.py
> +                except Exception:
Exception is too broad. You might be catching that's not intended to be caught here.
Use `except PermissionError` to be specific.

2020-10-14 05:56 UTC, k4yt3x commented on src/upscaler.py
> +                            Avalon.info(_("Remove file:[%s] readOnly attribute." % file))
Formatting should happen outside of the gettext function. Also, `%` operator is an outdated method. Use `.format`.
Also, please be consistent with your use of quotation marks. This project uses single quotes.
e.g., `Avalon.info(_('Removing read-only attribute from file {}').format(file))`

2020-10-14 05:56 UTC, k4yt3x commented on src/upscaler.py
> +                        for file in self.extracted_frames.iterdir():
Historically, `file` was a keyword, an alias for `open.
I would recommend using something more specific like `extracted_frame`.

2020-10-14 05:56 UTC, k4yt3x commented on src/upscaler.py
> +                            os.chmod(file, stat.S_IWRITE)
This is a file object operation, so it should be handled by the file object.
Use `extracted_frame.chmod`.

2020-10-14 05:56 UTC, k4yt3x commented on src/upscaler.py
> +import os
Remove this redundant import.

2020-10-14 05:56 UTC, k4yt3x commented on src/upscaler.py
> +                            Avalon.info(_("Remove file:[%s] readOnly attribute." % file))
Also are you sure that you'll want to print this out?
Even if you do, it shouldn't be `Avalon.info` but `Avalon.debug_info`.
This shouldn't have a vibrant color and get outputted to stdout.

2020-10-14 05:56 UTC, k4yt3x commented on src/upscaler.py
> +                        shutil.rmtree(self.extracted_frames)
What if it's not windows? You need to throw the exception again, otherwise it will keep on going ignoring the errors.

2020-10-14 05:58 UTC, k4yt3x commented
Your commit messages need to be more meaningful as well.

2020-10-14 06:06 UTC, k4yt3x commented
I'm hesitating to merge this PR. If a user has set read-only permissions on a file or folder/directory, program should be expected to respect those permissions instead of altering them without notifying the user.

2020-10-14 23:52 UTC, k4yt3x commented
@RhynarAI please take a look at this.

2020-10-15 02:21 UTC, zxsean commented
Not particularly good at python~~233.
i will fix these.

2020-10-15 02:29 UTC, k4yt3x commented
@zxsean you can wait until @jekabsmilbrets provides the necessary supplemental information.
@RhynarAI also needs to review this.

2020-10-15 02:30 UTC, zxsean commented
Sure.

2020-10-15 11:17 UTC, RhynarAI commented
What I am thinkin of about is: How did the files get  the "read only" attribute in the first place? A temp folder for extracted frames should not have set these permissions by default, unless someone has weird user restrictions on certain directories, in which case he should change these user rights or use another directory..

2020-10-19 15:09 UTC, jekabsmilbrets commented
I tested on version 4.7.0 and it works perfectly!

2020-10-19 16:22 UTC, k4yt3x commented
@jekabsmilbrets Excellent.

I am closing this PR due to the following considerations:

- There is no evidence that Video2X or its components will change directory/file permissions. Therefore, there's no need altering any permissions.
- Default permissions and attributes of files and directories should be respected. An error should be thrown when the files/directories cannot be read/written instead of changing the file/directory attributes.

Thank you for opening this PR. Please leave additional comments if you'd like to.

2020-10-19 16:22 UTC, closed without merging